services:

  postgres:
    container_name: database
    image: 'postgres:16-alpine'
    networks:
      - empregos-net
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    container_name: back-end
    image: empregos/back-end
    depends_on:
      - postgres
    build:
      context: ./empregos-backend
      dockerfile: Dockerfile
    networks:
      - empregos-net
    ports:
      - '8080:8080'
    environment:
      - DEV_MODE=${DEV_MODE}
      - POSTGRES_URL=postgres:5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  frontend:
    container_name: front-end
    image: empregos/front-end
    depends_on:
      - backend
    build:
      context: ./empregos-frontend
      dockerfile: Dockerfile
    networks:
      - empregos-net
    ports:
      - '4200:4200'
    environment:
      - API_URL=http://backend:8080

networks:
  empregos-net:
    driver: bridge