services:

  postgres:
    container_name: database
    image: 'postgres:16'
    networks:
      - empregos-net
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    container_name: back-end
    image: 'caruazu/empregos-backend:0.2'
    depends_on:
      - postgres
    networks:
      - empregos-net
    ports:
      - '8080:8080'
    environment:
      - DEV_MODE=${DEV_MODE}
      - FRONT_END_URL=http://192.168.0.111:4200
      - POSTGRES_URL=postgres:5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  frontend:
    container_name: front-end
    image: 'caruazu/empregos-frontend:0.2'
    depends_on:
      - backend
    networks:
      - empregos-net
    ports:
      - '4200:4200'

networks:
  empregos-net:
    driver: bridge